### PR TITLE
Remove openblas as anaconda recipe due to conflicts with conda-forge/armadillo.

### PR DESCRIPTION
**Pull request by dirmeier**
Having openblas on anaconda leads to conflicts when using openblas and armadillo as requirements on bioconda recipes. That is, one gets pulled from anaconda, while the other is pulled from conda-forge. Removing openblas from anaconda will resolve this.

### CODE REVIEW

**Comment by mingwandroid** [comment]
I'm sorry but there is no way we are going to remove packages because they are also on conda-forge.

**Comment by dirmeier** [comment]
Alright, I understand. Is adding armadillo here an option, then? This would also work fine.

**Comment by ccordoba12** [comment]
`openblas` is also part of conda-forge too:

https://github.com/conda-forge/openblas-feedstock

so this could be a bug in conda? I mean, it seems conda is not pulling `openblas` from the right channel. What is your conda version?

**Comment by dirmeier** [comment]
It is not a bug in conda, I think, but with pulling from different channels. I.e. if I pull `boost/armadillo` from conda-forge and `openblas` from defaults, I get linker errors.  This happens for bioconda builds where the channel priority is: `defaults` > `conda-forge`. If I do it locally on my machine, where I can set the priorities myself (i.e. `conda-forge` > `defaults`), this is not an issue. Only if I use the bioconda travis checks.  

The only solution, I think is, to install all dependencies/recipes on all channels or only on one channel.

Or am I wrong here?

**Comment by ccordoba12** [comment]
No, you're not wrong. You *can't* mix packages from `defaults` and `conda-forge` because they have different build specifications.

Please see this https://github.com/conda-forge/boost-feedstock/pull/15#issuecomment-251734905 for an explanation.

In essence, you need to install conda-forge packages in a different conda environment from the root one.

**Comment by dirmeier** [comment]
Alright, so if I had all the right packages in the same channel should be working. For `bioconda` travis-builds this is an issue as I mentioned. Would it be ok for you if I created a pull-request that adds `armadillo` to `anaconda`?

**Comment by ccordoba12** [comment]
> Would it be ok for you if I created a pull-request that adds armadillo to anaconda?

Sorry, we don't accept PRs to add new packages to Anaconda.

If bioconda is a different channel from conda-forge, and you have permissions to add packages to it, then you could move any conda-forge package to bioconda. That would solve your problem.

**Pull request closed without merging**
