### PR TITLE
Update gensim to 3.0.1

### PR DESCRIPTION
**Pull request by menshikh-iv**

### CODE REVIEW

**Comment by mingwandroid** [comment]
Thanks @menshikh-iv, we no longer use this repository (and didn't really use it much anyway).

Our recipe for gensim is here: https://github.com/AnacondaRecipes/gensim-feedstock which is forked from https://github.com/conda-forge/gensim-feedstock. The best course of action is to make a PR to conda-forge then we will rebase our fork on top of that.

**Comment by menshikh-iv** [comment]
Thank you @mingwandroid,
I already update https://github.com/conda-forge/gensim-feedstock, what's I need to do now (and in future)?

**Comment by mingwandroid** [comment]
You don't need to do anything more. We will rebase on top of `conda-forge` when we can and do new builds. At present we're a bit busy with other things though.

**Comment by menshikh-iv** [comment]
Thanks @mingwandroid , I hope in future this procedure will be automatic :start:

**Comment by mingwandroid** [comment]
Indeed! Me too.

**Pull request closed without merging**
