### PR TITLE
update orange3 recipe

### PR DESCRIPTION
**Pull request by astaric**
Fix orange3

Current build does not show any icons (missing joblib dependency) and does not use the stylesheet (manually disabled with pkg_res.patch).

I have added joblib to the list of dependencies and removed the patch, as it no longer seems necessary. (I guess it was related to biolab/orange3#1007, fixed in biolab/orange3#1006)

I have also bumped Orange to 3.3.6, as it is the latest stable release.

### CODE REVIEW

**Comment by ilanschnell** [comment]
Thanks

**Comment by ilanschnell** [comment]
I've uploaded new packages to the default repo.  Can you verify that the problem is fixed?
Also, is `orange3` only for Python 3?  We currently use `orange` for Python 2:
https://pypi.python.org/pypi/Orange/2.7.8
I'm confused about the relation between those projects, and it would be nice if we could just use `orange3`.

Thanks

**Comment by astaric** [comment]
It works now.

I still had to use a [workaround](https://github.com/ContinuumIO/anaconda-issues/issues/131#issuecomment-231009644) to make the icons show on osx, but if I understand correctly, that [will be fixed](https://github.com/ContinuumIO/anaconda-issues/issues/131#issuecomment-231147738) with the next build of pyqt.
On Ubuntu 16.04, everything works out of the box.

**Comment by astaric** [comment]
Orange3 is the new version of Orange and is python3-only. Orange (2.x) is the old version that contains its own implementations of algorithms (orange3 depends on scikit-learn) and is written in python2. Orange (2.x) is in maintenance mode and does not receive any new features while orange3 is actively developed with regular (monthly) releases.

**Comment by ajdapretnar** [comment]
@ilanschnell Orange is now already on 3.3.7. Is there any way Anaconda would automatically update Orange versions, or should we submit PRs with every new release? @astaric informed me there's a conda-forge channel for latest versions, but I reckon it would make sense to show the latest release also on [Anaconda website](https://anaconda.org/anaconda/orange3). Thanks!

**Pull request merged**
