### PR TITLE
Fix readline's ncurses linkage under Linux

### LINKED ISSUE #56: (linux-64) readline 6.2 has undefined symbols
I ran into a problem when I attempted to link against readline. The package coming from the defaults channel is not linked against `ncurses` and `tinfo`, so you end up with this:
```
$ ldd -r $CONDA_PREFIX/../../lib/libreadline.so.6.2
	linux-vdso.so.1 =>  (0x00007ffd2b35f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb61ab23000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003aa5400000)
undefined symbol: PC	(/internal/1/jhunk/miniconda3/lib/libreadline.so.6.2)
undefined symbol: UP	(/internal/1/jhunk/miniconda3/lib/libreadline.so.6.2)
undefined symbol: BC	(/internal/1/jhunk/miniconda3/lib/libreadline.so.6.2)
undefined symbol: tgetflag	(/internal/1/jhunk/miniconda3/lib/libreadline.so.6.2)
undefined symbol: tgetent	(/internal/1/jhunk/miniconda3/lib/libreadline.so.6.2)
undefined symbol: tputs	(/internal/1/jhunk/miniconda3/lib/libreadline.so.6.2)
undefined symbol: tgoto	(/internal/1/jhunk/miniconda3/lib/libreadline.so.6.2)
undefined symbol: tgetnum	(/internal/1/jhunk/miniconda3/lib/libreadline.so.6.2)
undefined symbol: tgetstr	(/internal/1/jhunk/miniconda3/lib/libreadline.so.6.2)
```

As a test I installed readline from conda-forge and linked against it without any problems. It doesn't seem to be linked against Continuum (or conda-forge's) ncurses, but maybe that's by design.

From "conda-forge" readline-6.3 package:
```
$ ldd -r $CONDA_PREFIX/lib/libreadline.so.6.3
	linux-vdso.so.1 =>  (0x00007fff831a9000)
	libncurses.so.5 => /lib64/libncurses.so.5 (0x00007fc1a1a80000)
	libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007fc1a185e000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc1a14ca000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc1a12c6000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003aa5400000)
```

I would prefer to avoid providing conda-forge as a solution to my coworkers, because it introduces a lot more than just "readline". It could cause conflicts/bugs with the software developed to work specifically with the defaults channel.

### PR DESCRIPTION
**Pull request by jhunkeler**
Fixes #56

### CODE REVIEW

**Comment by jhunkeler** [comment]
@mingwandroid I notice you are assigned to #56. Without touching anything else, the changes I've made were enough to produce an ncurses-capable readline package.

**Comment by elehcim** [comment]
@jhunkeler Thanks, I built a readline package using your patch, hosted it on my conda channel and it solved the linkage problems I was having. I hope this would be merged soon.

**Comment by eteq** [comment]
@ilanschnell - any chance of getting this in?  It looks like it's likely to address ContinuumIO/anaconda-issues#44, which would seem to help a lot of people...

**Comment by johanneskoester** [comment]
Continuum, any comment on this?

**Pull request closed without merging**
