### PR TITLE
Re-organize recipes for glueviz

### PR DESCRIPTION
**Pull request by astrofrog**
glueviz is now a metapackage that depends on glue-core (formerly the glueviz package) and glue-vispy-viewers (which provides the 3D functionality). The glueviz package is the main package for the glue project, and is the one that most users should install. The order for building the packages (the first time) is glue-core, then glue-vispy-viewers, then glueviz.

This avoids the circular dependencies that were being introduced in #83 and #84.

cc @ccordoba12 @ilanschnell

### CODE REVIEW

**Comment by ccordoba12** [comment]
I could migrate these recipes to our internal repo. @ilanschnell?

**Comment by astrofrog** [comment]
@ccordoba12 @ilanschnell - any updates on this? It would be great to have the latest versions of glue in defaults, as currently users are getting confused as to why they only see version 0.9.1 there.

**Comment by csoja** [comment]
@ccordoba12 can you open a PR on the internal repo?

**Comment by astrofrog** [comment]
Are there any updates on this? Thanks!

**Comment by ccordoba12** [comment]
@astrofrog, sorry for the huge delay on looking at this.

@csoja, do we have time to update Glue before the release of Anaconda 4.4?

**Comment by astrofrog** [comment]
Note that glue-core and glueviz both have a 0.10.4 release now so the recipes would need to be updated - not sure if it's useful for me to do that here though since it sounds like you have an internal repo?

**Comment by csoja** [comment]
glueviz is not included in the Anaconda v4.4 installer.  I'll add this to the list to update in repo.continuum.io - a PR to this repo is helpful, as it will make it quicker for us to build the packages.

**Comment by astrofrog** [comment]
@csoja - this PR should now be up-to-date. Is there anything else I can do to help this move forward?

**Comment by ccordoba12** [comment]
I submitted a PR against our internal repo and verified that it works with conda-build without problems.

However, I really don't know when new packages will be uploaded to our repos.

**Comment by ilanschnell** [comment]
Thanks!

**Pull request merged**
