### PR TITLE
Update yt recipe for 3.3.1

### PR DESCRIPTION
**Pull request by ngoldbaum**
The tests just check if various cython modules can be imported. Given that we've renamed some of them and that merely importing "yt" will cause these to be imported, I've just deleted the module import tests.

Note that the updated recipe largely reflects the one over at conda-forge: https://github.com/conda-forge/yt-feedstock

It would be great if whoever is in charge of the default anaconda channel could update the yt package using this recipe!

### CODE REVIEW

**Comment by ngoldbaum** [comment]
I chatted with @msarahan at SciPy about this - his advice was to open a PR here to let Continuum know about the yt release so yt can be updated in the default anaconda channel. Please let me know if there's a better way to communicate about releases.

**Comment by msarahan** [comment]
Ping @csoja @ilanschnell

**Comment by ilanschnell** [comment]
Thanks

**Comment by ilanschnell** [comment]
`yt 3.3.1` is now availabe

**Pull request merged**
